"""AN OPULENT SIEGE UPON THE DRUNKARD KING
Netherwalker x MySpace Deathcore Revival (2026).

Every guitar riff is generated by the tab-first engine (riffgen.py): rhythm
masks sampled from the mined era canon, fret walks from the mined bigram
tables, Easley two-part schemes, playability-validated, exported as ASCII
tab (docs/tabs-song4.txt) for human inspection.

Era law (docs/15): Drop A# 6-string, blast-in, chromatic verse, two-step,
AtG tremolo leitmotif (the "orchestra"), 8th-note mid breakdown, a-cappella
pickup, slower final breakdown with pinch squeals, dead stop. ~3:10.
Scrappy humanization ON (this is the pre-quantize era).
"""

from score import Score, Note, humanize
from riffgen import make_riff, make_tremolo, midi_of, TUNING
import random

random.seed(45)
RNG = random.Random(45)

TITLE = "an_opulent_siege_upon_the_drunkard_king"
MIX_PROFILE = "raw2007"

BAR = 4.0
A_SH = TUNING[0]         # A#1 = 34


def bars(n):
    return n * BAR


class Siege:
    def __init__(self):
        self.s = Score()
        self.s.tempo_map = []
        lengths = dict(taverne=4, verse1=25, twostep=16, tremverse=16,
                       midbreak=12, bridge=16, pickup=2, finalbreak=12,
                       out=2)
        self.sec = {}
        pos = 0.0
        for k, v in lengths.items():
            self.sec[k] = pos
            pos += bars(v)
        self.s.set_tempo(0.0, 115.0)
        self.s.set_tempo(self.sec["verse1"], 230.0)
        self.s.set_tempo(self.sec["twostep"], 200.0)
        self.s.set_tempo(self.sec["tremverse"], 230.0)
        self.s.set_tempo(self.sec["midbreak"], 120.0)
        self.s.set_tempo(self.sec["bridge"], 230.0)
        self.s.set_tempo(self.sec["pickup"], 120.0)
        self.s.set_tempo(self.sec["finalbreak"], 100.0)
        for nm in ("gtr_l", "gtr_r", "lead", "clean", "bass", "drums"):
            setattr(self, nm, self.s.track(nm))
        self.tabs = []

    # ------------------------------------------------------------- helpers
    def drum(self, t, name, vel, dur=0.2, grid=False):
        tags = {name, "grid"} if grid else {name}
        self.drums.notes.append(Note(t, dur, 0, vel, frozenset(tags)))

    def play_riff(self, riff, t0, reps=1, vel=106, kick_follow=False,
                  pinch_vel=118, label=""):
        """Render a Riff (tab-space) onto both guitars + bass."""
        self.tabs.append((label or riff.kind, riff.tempo, riff.tab()))
        nb = len(riff.bars)
        for rep in range(reps):
            for b, (mask, frets, pinch) in enumerate(riff.bars):
                base = t0 + (rep * nb + b) * BAR
                slots = sorted(frets)
                for idx, i in enumerate(slots):
                    t = base + i * 0.25
                    nxt = slots[idx + 1] if idx + 1 < len(slots) else 16
                    gap = (nxt - i) * 0.25
                    dur = min(gap * 0.8, 0.45 if gap <= 0.5 else 1.6)
                    pitch = midi_of(riff.string, frets[i])
                    ring = gap > 0.75
                    art = "sus" if ring else "pm"
                    for tr in (self.gtr_l, self.gtr_r):
                        tr.add(t, dur, pitch, vel + (6 if i == 0 else 0)
                               + (4 if ring else 0), art)
                    if pinch == i:
                        self.gtr_l.add(t + 0.02, 1.0, pitch + 24, pinch_vel,
                                       "pinch")
                    self.bass.add(t, dur * 1.1, max(28, pitch - 12),
                                  vel + 8, "pm")
                    if kick_follow:
                        self.drum(t, "kick", 116, dur=0.1, grid=True)

    # --------------------------------------------------------- era drums
    def era_blast(self, t0, nbars, vel=104):
        """2007 blast at ~230: snare on 8ths, kick on off-8ths, ride 8ths.
        Scrappy — humanized, velocities loose."""
        for i in range(int(nbars * 8)):
            t = t0 + i * 0.5
            self.drum(t, "snare", vel + RNG.randint(-8, 6))
            self.drum(t + 0.25, "kick", 108 + RNG.randint(-4, 4), dur=0.1)
            self.drum(t, "ride", 84 + (10 if i % 4 == 0 else 0))

    def dbeat(self, t0, nbars):
        """Two-step punk beat: kick 1 & 3&, snare 2 & 4, crash-ride 8ths."""
        for b in range(int(nbars)):
            base = t0 + b * BAR
            for tt in (0.0, 1.75, 2.0, 3.75):
                self.drum(base + tt, "kick", 112, dur=0.12)
            self.drum(base + 1.0, "snare", 116 + RNG.randint(-4, 4))
            self.drum(base + 3.0, "snare", 118 + RNG.randint(-4, 4))
            for e in range(8):
                self.drum(base + e * 0.5, "hihat_closed", 88 + (e % 2) * -10)

    def halftime(self, t0, nbars, china=True):
        for b in range(int(nbars)):
            base = t0 + b * BAR
            self.drum(base + 2.0, "snare", 121)
            if china:
                for q in range(4):
                    self.drum(base + q, "china", 100 + (q == 0) * 8)

    def fill_simple(self, t0):
        for i, d in enumerate(("snare", "snare", "tom2", "tom_floor")):
            self.drum(t0 + i * 0.25, d, 102 + i * 4)

    # ------------------------------------------------------------- build
    def build(self):
        self.taverne(); self.verse1(); self.twostep(); self.tremverse()
        self.midbreak(); self.bridge(); self.pickup(); self.finalbreak()
        self.outro()
        # era feel: everything humanized, including drums (pre-quantize era)
        self.drums.notes = humanize(self.drums.notes, vel_jitter=7,
                                    time_jitter_beats=0.010,
                                    keep_grid=("grid",))
        for tr in (self.gtr_l, self.gtr_r):
            tr.notes = humanize(tr.notes, vel_jitter=7,
                                time_jitter_beats=0.008)
            tr.notes = [Note(n.start, n.dur * RNG.uniform(0.92, 1.06),
                             n.pitch, n.vel, n.tags) for n in tr.notes]
        self.bass.notes = humanize(self.bass.notes, vel_jitter=5,
                                   time_jitter_beats=0.006)
        return self.s

    def taverne(self):
        """Era clean intro (<=10 s): lone tavern arpeggio; a mono lo-fi
        movie/lore sample goes here at vocal tracking time."""
        t0 = self.sec["taverne"]
        arp = [(0, 34 + 12), (0.5, 34 + 19), (1.0, 34 + 22), (1.5, 34 + 19),
               (2.0, 34 + 24), (2.5, 34 + 22), (3.0, 34 + 19), (3.5, 34 + 15)]
        for b in range(3):
            for tt, p in arp:
                self.clean.add(t0 + b * BAR + tt, 0.9, p - (2 if b == 2 else 0),
                               78 + RNG.randint(-6, 6), "clean")
        self.lead.add(t0 + bars(2), bars(2), 34 + 30, 62, "vib")  # feedback
        self.fill_simple(t0 + bars(3) + 3.0)

    def verse1(self):
        """Blast-in + chromatic chug verse (the mined-mask riff), 8 bars."""
        t0 = self.sec["verse1"]
        self.drum(t0, "crash1", 116)
        for i in range(4):                     # 1-bar blast-in fill
            self.drum(t0 + 3.0 + i * 0.25, "snare", 96 + i * 8)
        r = make_riff(RNG, "chug", 230, max_pcs=3)
        self.play_riff(r, t0 + bars(1), reps=6, label="verse1 chug")
        self.era_blast(t0 + bars(1), 24)

    def twostep(self):
        t0 = self.sec["twostep"]
        self.drum(t0, "crash2", 114)
        r = make_riff(RNG, "twostep", 200)
        self.play_riff(r, t0, reps=4, label="two-step")
        self.dbeat(t0, 14)
        # bars 7-8: gang-shout slot — riff thins to hits on 1
        for b in (14, 15):
            self.drum(t0 + bars(b), "china", 112)
            self.drum(t0 + bars(b), "kick", 118, dur=0.12, grid=True)
        self.fill_simple(t0 + bars(15) + 3.0)

    def tremverse(self):
        """The leitmotif: AtG tremolo line (this IS the orchestra)."""
        t0 = self.sec["tremverse"]
        r = make_tremolo(RNG, 230, nbars=4, string=2, base_fret=3)
        self.tabs.append(("leitmotif tremolo", 230, r.tab()))
        for rep in range(4):
            for b, (mask, frets, _) in enumerate(r.bars):
                base = t0 + (rep * 4 + b) * BAR
                for i in range(16):
                    p = midi_of(2, frets[i])
                    v = 96 + (0 if i % 2 == 0 else -12) + RNG.randint(-4, 4)
                    self.gtr_l.add(base + i * 0.25, 0.24, p, max(40, v), "trem")
                    self.gtr_r.add(base + i * 0.25, 0.24, p, max(40, v), "trem")
                self.bass.add(base, BAR * 0.95, A_SH - 12 + (0 if b < 3 else 1),
                              104, "sus")
        self.era_blast(t0, 16, vel=102)

    def midbreak(self):
        """Mid breakdown: mined sparse grid, kick follows, squeal every
        2 bars, china quarters."""
        t0 = self.sec["midbreak"]
        self.drum(t0, "china", 114)
        r = make_riff(RNG, "breakdown", 120)
        self.play_riff(r, t0, reps=3, kick_follow=True, vel=112,
                       label="mid breakdown")
        self.halftime(t0, 12)

    def bridge(self):
        """Tremolo chorus, harmonized in diatonic 3rds (era melodeath)."""
        t0 = self.sec["bridge"]
        self.drum(t0, "crash1", 114)
        r = make_tremolo(RNG, 230, nbars=4, string=2, base_fret=3)
        self.tabs.append(("bridge harmony (gtr2 +3rd)", 230, r.tab()))
        minor_pcs = {(A_SH + o) % 12 for o in (0, 2, 3, 5, 7, 8, 10)}
        for rep in range(4):
            for b, (mask, frets, _) in enumerate(r.bars):
                base = t0 + (rep * 4 + b) * BAR
                for i in range(16):
                    p = midi_of(2, frets[i])
                    h = p + (3 if (p + 3) % 12 in minor_pcs else 4)
                    v = 96 + (0 if i % 2 == 0 else -12) + RNG.randint(-4, 4)
                    self.gtr_l.add(base + i * 0.25, 0.24, p, max(40, v), "trem")
                    self.gtr_r.add(base + i * 0.25, 0.24, h, max(40, v - 4),
                                   "trem")
                self.bass.add(base, BAR * 0.95, A_SH - 12, 104, "sus")
        self.era_blast(t0, 14, vel=100)
        self.halftime(t0 + bars(14), 2, china=True)

    def pickup(self):
        """A-cappella scream pickup: near silence, one lone chug + feedback."""
        t0 = self.sec["pickup"]
        for tr in (self.gtr_l, self.gtr_r):
            tr.add(t0, 0.5, A_SH, 108, "pm")
        self.bass.add(t0, 0.6, A_SH - 12, 110, "pm")
        self.drum(t0, "kick", 118, dur=0.12, grid=True)
        self.drum(t0, "crash1_stop", 108)
        self.lead.add(t0 + 1.0, bars(1.5), A_SH + 25, 66, "vib")  # feedback b2

    def finalbreak(self):
        """Final breakdown at 100: the '-1' — slower, sparser, squeals as
        punctuation, one slam slide, dead-stop end."""
        t0 = self.sec["finalbreak"]
        r = make_riff(RNG, "final_breakdown", 100, max_pcs=3)
        self.play_riff(r, t0, reps=2, kick_follow=True, vel=114,
                       label="final breakdown")
        self.halftime(t0, 8)
        # squeal punctuation every 2 bars (era law)
        for b in (1, 3, 5):
            self.gtr_l.add(t0 + bars(b) + 3.0, 1.0, A_SH + 24, 120, "pinch")
        # one slam scoop: slide into the low chord, bar 7
        for tr in (self.gtr_l, self.gtr_r):
            tr.add(t0 + bars(6), 1.5, A_SH + 1, 116, "slide", "sus")
        self.bass.add(t0 + bars(6), 1.5, A_SH - 11, 112, "pick")
        # bars 9-10: half-density, then THE dead stop
        for b, tt_list in ((8, (0.0, 2.0)), (9, (0.0, 2.0)),
                           (10, (0.0,)), (11, (0.0,))):
            for tt in tt_list:
                for tr in (self.gtr_l, self.gtr_r):
                    tr.add(t0 + bars(b) + tt, 0.5, A_SH, 116, "pm")
                self.bass.add(t0 + bars(b) + tt, 0.6, A_SH - 12, 114, "pm")
                self.drum(t0 + bars(b) + tt, "kick", 120, dur=0.12, grid=True)
                self.drum(t0 + bars(b) + tt, "china", 110)
            self.drum(t0 + bars(b) + 2.0, "snare", 122)

    def outro(self):
        """Dead stop. One bar of feedback decay — era ending."""
        t0 = self.sec["out"]
        self.lead.add(t0, bars(1), A_SH + 30, 58, "vib")


def build_song():
    s4 = Siege()
    score = s4.build()
    # export tabs for human inspection
    import os
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(repo, "docs", "tabs-song4.txt"), "w") as f:
        f.write("AN OPULENT SIEGE UPON THE DRUNKARD KING — generated tabs\n"
                "(Drop A#: A#-F-A#-D#-G-C, low to high)\n\n")
        for label, tempo, tab in s4.tabs:
            f.write(f"== {label} @ {tempo} BPM\n{tab}\n\n")
    return score, s4.sec
